[book]
authors = ["kgv"]
description = ""

[preprocessor.katex]
after = ["links"]
before = ["gettext"]
renderers = ["epub", "html", "pdf"]

[preprocessor.gettext]
after = ["links"]

[build]
extra-watch-dirs = ["po"]

[output.html]
additional-css = ["theme/css/language-picker.css"]
git-repository-url = "https://github.com/ippras/fatty_acid_expressions"
hash-files = true

[output.html.fold]
enable = true
level = 2

[output.markdown]

# [output.epub]

# [output.pdf]
