[formatting]
reorder_arrays = true
reorder_keys = true

# https://doc.rust-lang.org/cargo/reference/manifest.html
[[rule]]
include = ["**/Cargo.toml"]
keys = ["package"]
formatting = { reorder_keys = false }

# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
[[rule]]
include = ["**/rust-toolchain.toml"]
formatting = { reorder_arrays = false, reorder_keys = false }

[[rule]]
include = ["**/taplo.toml"]
formatting = { reorder_arrays = false, reorder_keys = false }
