BhattacharyyaDistance = Bhattacharyya distance
ChebyshevDistance = Chebyshev distance
CosineDistance = Cosine distance
EuclideanDistance = Euclidean distance
HellingerDistance = Hellinger distance
JaccardDistance = Jaccard distance
JensenShannonDistance = Jensen shannon distance
ManhattanDistance = Manhattan distance
OverlapDistance = Overlap distance
PearsonCorrelation = Pearson correlation
SpearmanRankCorrelation = Spearman rank correlation
