Math_Correlations_Pearson =
    .hover = Коэффициент корреляции Пирсона
Math_Correlations_Spearman =
    .hover = Spearman's rank correlation coefficient
Math_Moments_Kurtosis =
    .hover = Kurtosis
Math_Moments_Skewness =
    .hover = Skewness
Math_Distances_DataAnalysis_AnderbergSimilarity =
    .hover = Anderberg similarity
Math_Distances_DataAnalysis_BraunBlanquetSimilarity =
    .hover = Braun–Blanquet similarity
Math_Distances_DataAnalysis_DispersionSimilarity =
    .hover = Dispersion similarity
Math_Distances_DataAnalysis_FaithSimilarity =
    .hover = Faith similarity
Math_Distances_DataAnalysis_ForbesMozleySimilarity =
    .hover = Forbes–Mozley similarity
Math_Distances_DataAnalysis_GowerLegendreSimilarity =
    .hover = Gower–Legendre similarity
Math_Distances_DataAnalysis_GowerSimilarity_2 =
    .hover = Gower similarity 2
Math_Distances_DataAnalysis_HamannSimilarity =
    .hover = Hamann similarity
Math_Distances_DataAnalysis_ModelDistance =
    .hover = Model distance
Math_Distances_DataAnalysis_MountfordSimilarity =
    .hover = Mountford similarity
Math_Distances_DataAnalysis_PatternDifference =
    .hover = Pattern difference
Math_Distances_DataAnalysis_PearsonPhiSimilarity =
    .hover = Pearson $\phi$ similarity
Math_Distances_DataAnalysis_Q_0Difference =
    .hover = $Q_0$-difference
Math_Distances_DataAnalysis_RandSimilarity =
    .hover = Rand similarity
Math_Distances_DataAnalysis_RogerTanimotoSimilarity =
    .hover = Roger–Tanimoto similarity
Math_Distances_DataAnalysis_RusselRaoSimilarity =
    .hover = Russel–Rao similarity
Math_Distances_DataAnalysis_SokalSneathSimilarities =
    .hover = Sokal–Sneath similarities
Math_Distances_DataAnalysis_TverskySimilarity =
    .hover = Tversky similarity
Math_Distances_DataAnalysis_YuleSimilarities =
    .hover = Yule similarities
Math_Distances_DataAnalysis_CosineSimilarity =
    .hover = Cosine similarity
Math_Distances_DataAnalysis_CovarianceSimilarity =
    .hover = Covariance similarity
Math_Distances_DataAnalysis_GlobalCorrelationDistance =
    .hover = Global correlation distance
Math_Distances_DataAnalysis_LogLikelihoodDistance =
    .hover = Log-likelihood distance
Math_Distances_DataAnalysis_MorisitaHornSimilarity =
    .hover = Morisita–Horn similarity
Math_Distances_DataAnalysis_PearsonCorrelationSimilarity =
    .hover = Pearson correlation similarity
Math_Distances_DataAnalysis_SimilarityRatio =
    .hover = Similarity ratio
Math_Distances_DataAnalysis_SpearmanRankCorrelation =
    .hover = Spearman rank correlation
Math_Distances_DataAnalysis_BaroniUrbaniBuserSimilarity =
    .hover = Baroni–Urbani–Buser similarity
Math_Distances_DataAnalysis_BrayCurtisSimilarity =
    .hover = Bray–Curtis similarity
Math_Distances_DataAnalysis_CanberraDistance =
    .hover = Canberra distance
Math_Distances_DataAnalysis_CzekanowskyDiceDistance =
    .hover = Czekanowsky–Dice distance
Math_Distances_DataAnalysis_CzekanowskySimilarity =
    .hover = Czekanowsky similarity
Math_Distances_DataAnalysis_DiceSimilarity =
    .hover = Dice similarity
Math_Distances_DataAnalysis_EllenbergSimilarity =
    .hover = Ellenberg similarity
Math_Distances_DataAnalysis_GleasonSimilarity =
    .hover = Gleason similarity
Math_Distances_DataAnalysis_IntersectionDistance =
    .hover = Intersection distance
Math_Distances_DataAnalysis_JaccardSimilarity =
    .hover = Jaccard similarity
Math_Distances_DataAnalysis_KulczynskiSimilarity_1 =
    .hover = Kulczynski similarity 1
Math_Distances_DataAnalysis_KulczynskiSimilarity_2 =
    .hover = Kulczynski similarity 2
Math_Distances_DataAnalysis_MarylandBridgeSimilarity =
    .hover = Maryland Bridge similarity
Math_Distances_DataAnalysis_MotykaSimilarity =
    .hover = Motyka similarity
Math_Distances_DataAnalysis_RobertsSimilarity =
    .hover = Roberts similarity
Math_Distances_DataAnalysis_RuzickaSimilarity =
    .hover = Ruzicka similarity
Math_Distances_DataAnalysis_SimpsonSimilarity =
    .hover = Simpson similarity
Math_Distances_DataAnalysis_S_rensenDistance =
    .hover = Sørensen distance
Math_Distances_DataAnalysis_BinaryEuclideanDistance =
    .hover = Binary Euclidean distance
Math_Distances_DataAnalysis_ClarkDistance =
    .hover = Clark distance
Math_Distances_DataAnalysis_EffectSize =
    .hover = Effect size
Math_Distances_DataAnalysis_HellingerDistance =
    .hover = Hellinger distance
Math_Distances_DataAnalysis_LorentzianDistance =
    .hover = Lorentzian distance
Math_Distances_DataAnalysis_MahalanobisDistance =
    .hover = Mahalanobis distance
Math_Distances_DataAnalysis_MeanCensoredEuclideanDistance =
    .hover = Mean censored Euclidean distance
Math_Distances_DataAnalysis_MeehlDistance =
    .hover = Meehl distance
Math_Distances_DataAnalysis_MultiplicativeDistance =
    .hover = Multiplicative distance
Math_Distances_DataAnalysis_NormalizedLpDistance =
    .hover = Normalized lp-distance
Math_Distances_DataAnalysis_PenroseSizeAndShapeDistances =
    .hover = Penrose size and shape distances
Math_Distances_DataAnalysis_PowerPRDistance =
    .hover = Power (p, r)-distance
Math_Distances_DataAnalysis_SymmetricChi_2Distance =
    .hover = Symmetric $\chi^2$-distance
Math_Distances_DataAnalysis_SymmetricChi_2Measure =
    .hover = Symmetric $\chi^2$-measure
Math_Distances_DataAnalysis_WeightedEuclideanDistance =
    .hover = Weighted Euclidean distance
Math_Distances_DataAnalysis_YjhhrMetrics =
    .hover = YJHHR metrics
