Indices_Monounsaturated = Monounsaturated
    .abbreviation = MUFA
    .hover = Monounsaturated index.
Indices_Polyunsaturated = Polyunsaturated
    .abbreviation = PUFA
    .hover = Polyunsaturated index.
Indices_Saturated = Saturated
    .abbreviation = SFA
    .hover = Saturated index.
Indices_Trans = Trans
    .abbreviation = TFA
    .hover = Trans index.
Indices_Unsaturated = Unsaturated
    .abbreviation = UFA
    .hover = Unsaturated index.

Indices_Delta = Delta { $index }
Indices_Omega = Omega { $index }

Indices_EicosapentaenoicAndDocosahexaenoic = Eicosapentaenoic and Docosahexaenoic
    .hover = Sum of Eicosapentaenoic and Docosahexaenoic.
Indices_FishLipidQuality = Fish Lipid Quality
    .abbreviation = FLQ
    .hover = Fish Lipid Quality.
Indices_HealthPromotingIndex = Health Promoting Index
    .abbreviation = HPI
    .hover = Health Promoting Index.
Indices_HypocholesterolemicToHypercholesterolemic = Hypocholesterolemic to Hypercholesterolemic
    .abbreviation = H/H
    .hover = Hypocholesterolemic to Hypercholesterolemic.
Indices_IndexOfAtherogenicity = Index of Atherogenicity
    .abbreviation = IA
    .hover = Index of Atherogenicity.
Indices_IndexOfThrombogenicity = Index of Thrombogenicity
    .abbreviation = IT
    .hover = Index of Thrombogenicity.
Indices_LinoleicToAlphaLinolenic = Linoleic to αLinolenic
    .abbreviation = LA/ALA
    .hover = Linoleic to αLinolenic.
Indices_Polyunsaturated-6ToPolyunsaturated-3 = Polyunsaturated -6 to Polyunsaturated -3
    .abbreviation = PUFA-6/PUFA-3
    .hover = Polyunsaturated -6 to Polyunsaturated -3.
Indices_PolyunsaturatedToSaturated = Polyunsaturated to Saturated
    .abbreviation = PUFA/SFA
    .hover = Polyunsaturated to Saturated.
Indices_UnsaturationIndex = Unsaturation Index
    .abbreviation = UI
    .hover = Unsaturation Index.
