Language = Language
    .hover= Select language.
LeftPanel = Left panel
    .hover = Show/hide left panel.
ResetApplication = Reset application
    .hover= Reset application data.
ResetGui = reset GUI
    .hover= Reset application GUI.
Value = Value
    .hover = Value.
Species = Species
    .hover = Species.

### Settings

Composition = Composition
    .hover = Triacylglycerol composition.
Composition_Mass_Monospecific = Mono, mass
    .abbreviation = MMC
    .hover = Mass non-stereospecific composition.
Composition_Mass_Stereospecific = Stereo, mass
    .abbreviation = SMC
    .hover = Mass stereospecific composition (agregation).
Composition_EquivalentCarbonNumber_Monospecific = Mono, ECN
    .abbreviation = MNC
    .hover = Equivalent carbon number non-stereospecific composition (agregation).
Composition_EquivalentCarbonNumber_Stereospecific = Stereo, ECN
    .abbreviation = SNC
    .hover = Equivalent carbon number stereospecific composition.
Composition_Species_Monospecific = Mono, species
    .abbreviation = MSC
    .hover = Species non-stereospecific composition (permutation).
Composition_Species_Positionalspecific = Positional, species
    .abbreviation = PSC
    .hover = Species positional specific composition (permutation).
Composition_Species_Stereospecific = Stereo, species
    .abbreviation = SSC
    .hover = Species stereospecific composition.
Composition_Type_Monospecific = Mono, type
    .abbreviation = MTC
    .hover = Type non-stereospecific composition (permutation).
Composition_Type_Positionalspecific = Positional, type
    .abbreviation = PTC
    .hover = Type positional specific composition (permutation).
Composition_Type_Stereospecific = Stereo, type
    .abbreviation = STC
    .hover = Type stereospecific composition.
Composition_Unsaturation_Monospecific = Mono, unsaturation
    .abbreviation = MUC
    .hover = Unsaturation non-stereospecific composition (agregation).
Composition_Unsaturation_Stereospecific = Stereo, unsaturation
    .abbreviation = SUC
    .hover = Unsaturation stereospecific composition.

DeltaDegreesOfFreedom = Delta Degrees of Freedom
    .abbreviation = DDOF
    .hover = The divisor used in calculations is N - DDOF, where N represents the number of elements. By default DDOF is zero.
    .info = Different values of the argument ddof are useful in different contexts.
Statistics = Statistics

Filter = Filter
    .hover = Filter rows by set operation.
Filter_Intersection = Intersection
    .hover = Non-zero values are present in all columns (AND).
Filter_Union = Union
    .hover = Non-zero values are present in one or more columns (OR).
Filter_Difference = Difference
    .hover = Non-zero values are missing in one or more columns (XOR).
Percent = Percent
    .hover = Display of values in percent.
Precision = Precision
    .hover = Number of decimal pieces.
Truncate = Truncate
    .hover = Truncate header text.
Sort = Sort
    .hover = Sort rows by.
Sort_Key = Key
    .hover = Sort by key.
Sort_Value = Value
    .hover = Sort by value.
Parameters = Parameters
Chaddock = Chaddock
    .hover = Chaddock scale.
Moments = Moments
Bias = Bias
    .hover = If False, then the calculations are corrected for statistical bias.
StandardDeviation = Standard deviation
FattyAcid = Fatty acid
Display = Display
    .hover = Display selected value in table.
Indices = Indices
    .hover = Display indices values in table.
Label = Label
Factor = Factor
    .hover = Enrichment factor or selectivity factor.
EnrichmentFactor = Enrichment factor
    .abbreviation = EF
    .hover = Enrichment factor.
SelectivityFactor = Selectivity factor
    .abbreviation = SF
    .hover = Selectivity factor.
NormalizeFactor = Normalize factor
    .hover = Normalize enrichment factor and selectivity factor.
Sample = Sample
    .hover = Sample.
Significant = Significant
    .hover = Round floating points to a number of significant figures.

Threshold = Threshold
    .hover = Values greater than or equal to the threshold value are major, values less than the threshold value are minor.
Threshold_IsAuto = Is auto
    .hover = Is auto threshold.
Threshold_Manual = Manual
    .hover = Manual threshold.
Threshold_Auto = Auto
    .hover = Auto threshold.
Threshold_Filter = Filter
    .hover = Filter minor fatty acids.
Threshold_Sort = Sort
    .hover = Sort by minor major.

# Metrics

BhattacharyyaDistance = Bhattacharyya distance
ChebyshevDistance = Chebyshev distance
CosineDistance = Cosine distance
EuclideanDistance = Euclidean distance
HellingerDistance = Hellinger distance
JaccardDistance = Jaccard distance
JensenShannonDistance = Jensen shannon distance
ManhattanDistance = Manhattan distance
OverlapDistance = Overlap distance
PearsonCorrelation = Pearson correlation
SpearmanRankCorrelation = Spearman rank correlation
